import subprocess
import sys
import os

# --------------------------
# Configuration
# --------------------------
ESP_PORT = "/dev/ttyUSB0"   # Replace with your ESP32 serial port
BAUD_RATE = "460800"        # Optional: adjust if needed

# Path to folder containing your Arduino .bin files
BIN_FOLDER = "/home/admin/project/tests"  # Example folder

# Filenames (as generated by Arduino IDE)
BOOTLOADER_BIN = "Blink.ino.bootloader.bin"
PARTITIONS_BIN = "Blink.ino.partitions.bin"
FIRMWARE_BIN = "Blink.ino.bin"

# --------------------------
# Flash function
# --------------------------
def flash_esp32(port, baud, folder, bootloader, partitions, firmware):
    # Build absolute paths
    bootloader_path = os.path.join(folder, bootloader)
    partitions_path = os.path.join(folder, partitions)
    firmware_path = os.path.join(folder, firmware)

    # Check that files exist
    for f in [bootloader_path, partitions_path, firmware_path]:
        if not os.path.exists(f):
            print(f"Error: {f} not found!")
            sys.exit(1)

    # Build esptool command
    cmd = [
        "esptool.py",
        "--chip", "esp32",
        "--port", port,
        "--baud", baud,
        "write_flash",
        "-z",
        "0x1000", bootloader_path,
        "0x8000", partitions_path,
        "0x10000", firmware_path
    ]

    print(f"Flashing ESP32 on {port}...")
    try:
        subprocess.run(cmd, check=True)
        print("Flash completed successfully! Press RESET on the ESP32 now.")
    except subprocess.CalledProcessError:
        print("Flashing failed!")
        sys.exit(1)

# --------------------------
# Main
# --------------------------
if __name__ == "__main__":
    flash_esp32(ESP_PORT, BAUD_RATE, BIN_FOLDER, BOOTLOADER_BIN, PARTITIONS_BIN, FIRMWARE_BIN)
