# This code will deal with data transfer to external microcontrollers via SPI.
# Data that will be trasnferred needs to be compiled previously, this means only .bin files can be transferred.
# ESP32 need .ino.bin, .ino.bootloader.bin and ino.partions.bin files to be transfered.

import subprocess
import sys
import os

# Configuration
ESP_PORT = "/dev/ttyUSB0"   # ESP32 serial port
BAUD_RATE = "460800"        

# Path to folder containing .bin files
BIN_FOLDER = "/home/admin/bachelor_project/bin_files"  # folder with .bin files

# Filenames (as generated by Arduino IDE)
BOOTLOADER_BIN = "Blink.ino.bootloader.bin"
PARTITIONS_BIN = "Blink.ino.partitions.bin"
FIRMWARE_BIN = "Blink.ino.bin"

# Find the name of .bin files
def find_bin_file(name):
    # This function will check the folder and will find three files with the exact name.
    # The files will have the endings .bootloader.bin, .partitions.bin and .bin respectively.
    # Then it will write the paths of these files to variables.

# Flash function
def flash_esp32(folder, bootloader, partitions, firmware):
    # Build absolute paths
    bootloader_path = os.path.join(folder, bootloader)
    partitions_path = os.path.join(folder, partitions)
    firmware_path = os.path.join(folder, firmware)

    # Check that files exist
    for f in [bootloader_path, partitions_path, firmware_path]:
        if not os.path.exists(f):
            print(f"Error: {f} not found!")
            sys.exit(1)

    # Build esptool command
    cmd = [
        "esptool.py",
        "--chip", "esp32",
        "--port", ESP_PORT,
        "--baud", BAUD_RATE,
        "write_flash",
        "-z",
        "0x1000", bootloader_path,
        "0x8000", partitions_path,
        "0x10000", firmware_path
    ]

    print(f"Flashing ESP32 on {ESP_PORT}...")
    try:
        subprocess.run(cmd, check=True)
        print("Flash completed successfully! Press RESET on the ESP32 now.")
    except subprocess.CalledProcessError:
        print("Flashing failed!")
        sys.exit(1)

# --------------------------
# Main
# --------------------------
if __name__ == "__main__":
    flash_esp32(BIN_FOLDER, BOOTLOADER_BIN, PARTITIONS_BIN, FIRMWARE_BIN)
